services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      # Используем переменные из .env файла
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  linkpulse.api:
    build:
      context: .
      dockerfile: LinkPulse.Api/Dockerfile
    depends_on:
      - postgres
      - rabbitmq

  linkpulse.worker:
    build:
      context: .
      dockerfile: LinkPulse.Worker/Dockerfile
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data: