services:
  postgres:
    ports:
      - "5435:5432"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  linkpulse.api:
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
  
  linkpulse.worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development