name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Сборка и публикация образа для API
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./LinkPulse.Api/Dockerfile 
          push: true 
          tags: ${{ secrets.DOCKER_USERNAME }}/linkpulse-api:latest

      # Сборка и публикация образа для Worker
      - name: Build and push Worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./LinkPulse.Worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/linkpulse-worker:latest