name: Release Server

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Convert image name to lowercase
        run: |
          echo "IMAGE_NAME=${REPO_NAME,,}" >>${GITHUB_ENV}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      #Сборка API
      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./LinkPulse.Api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/linkpulse-api:latest
      
      #Сборка Worker-а
      - name: Build and push Worker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./LinkPulse.Worker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/linkpulse-worker:latest
